name: Check Environment Variables

on: [push]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.dev.APP_ENV }}

jobs:
  check_variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check Environment Variables
        run: |

          echo $env_var
          printenv

