name: Check Environment Variables

on: [push]

jobs:
  check_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Check Environment Variables
        run: |
          echo "Workflow Environment Variables:"
          env

          echo "Organization and Repository Environment Variables:"
          echo "ORG_VARIABLE: ${{ env.ORG_VARIABLE }}"
          echo "REPO_VARIABLE: ${{ env.REPO_VARIABLE }}"