name: Check Environment Variables

on: [push]

jobs:
  check_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Check Environment Variables
        run: |
          echo "Workflow Environment Variables:"
          echo "ORG_VARIABLE: $repo_val"
        env:
          repo_val: ${{ vars }}
