name: Check Environment Variables

on: [push]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.APP_ENV_DEV }}

jobs:
  check_variables:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Check Environment Variables
        run: |

          echo $env_var

